version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  ngrok:
    image: ngrok/ngrok:latest
    command: http http://host.docker.internal:8080
    environment:
      - NGROK_AUTHTOKEN=2YFDG1bKRFpm7mnN7ox9_ETqksj2ycvt3pDqBud5p
    depends_on:
      - app
